spring.security.oauth2.resourceserver.jwt.issuer-uri=${ISSUER}
spring.datasource.url=${DB_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialec
spring.datasource.hikari.max-lifetime=480000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.keepalive-time=120000
spring.datasource.hikari.connection-test-query=SELECT 1
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
